#!/usr/bin/env python3
"""Push the operator ledger and STATUS snapshot to the HF output bucket.

Local Git keeps the authoritative ledger and GCS keeps run state; the bucket
copies under ``<output-bucket>/ops/`` are overwritable viewing copies for
operators (human or LLM) who work without this checkout. Only the two named
files are ever uploaded; credentials, run bindings and release directories are
never in scope. The ledger is validated and STATUS.md must carry the generated
banner before anything leaves the machine.

Renders the commands by default; ``--execute`` runs them.

Usage:
  python tools/push_ops.py                 # render what would be uploaded
  python tools/push_ops.py --execute       # upload via `hf buckets cp`
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import ledger  # noqa: E402  (local module, after path insert)

OUTPUT_BUCKET = "hf://buckets/Ligant/castle-output"
OPS_PREFIX = OUTPUT_BUCKET + "/ops"
STATUS_BANNER = "<!-- generated by tools/report.py; do not edit by hand -->"

UPLOADS = (
    (REPO / "ledger" / "ledger.jsonl", f"{OPS_PREFIX}/ledger.jsonl"),
    (REPO / "STATUS.md", f"{OPS_PREFIX}/STATUS.md"),
)


def local_checks() -> list[str]:
    problems = []
    for local, _ in UPLOADS:
        if not local.is_file():
            problems.append(f"missing local file: {local.relative_to(REPO)}")
    if not problems:
        rows = ledger.read(REPO / "ledger" / "ledger.jsonl")
        for index, row in enumerate(rows, 1):
            problems.extend(ledger.validate_record(row, index))
        if STATUS_BANNER not in (REPO / "STATUS.md").read_text(encoding="utf-8"):
            problems.append("STATUS.md lacks the generated banner; regenerate it with tools/report.py")
    return problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--execute", action="store_true",
                        help="Actually run the uploads; default only renders them")
    args = parser.parse_args(argv)

    problems = local_checks()
    if problems:
        print(json.dumps({"ok": False, "error": "LOCAL_CHECKS_FAILED",
                          "problems": problems[:10]}, indent=2, ensure_ascii=False))
        return 1

    commands = [["hf", "buckets", "cp", str(local), remote] for local, remote in UPLOADS]
    if not args.execute:
        print(json.dumps({"ok": True, "executed": False, "commands": commands},
                         indent=2, ensure_ascii=False))
        return 0
    for command, (local, _) in zip(commands, UPLOADS):
        done = subprocess.run(command, capture_output=True, text=True, check=False)
        if done.returncode != 0:
            print(json.dumps({"ok": False, "error": "UPLOAD_FAILED",
                              "file": local.name,
                              "detail": done.stderr.strip()[-300:]}, indent=2))
            return 1
    print(json.dumps({"ok": True, "executed": True, "prefix": OPS_PREFIX,
                      "files": [local.name for local, _ in UPLOADS],
                      "note": "Overwritable viewing copies; local Git and GCS state remain authoritative"},
                     indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
