#!/usr/bin/env python3
"""Render STATUS.md from the ledger plus a live cloud probe (R-09).

Every cloud fact in the output carries the probe timestamp, so no assertion in
the generated document can silently become stale prose. Never edit STATUS.md by
hand: rerun this instead.

Usage:
  python tools/report.py                     # probe the cloud, write STATUS.md
  python tools/report.py --from-json probe.json --out STATUS.md
  python tools/report.py --check             # fail if STATUS.md is out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

DEFAULT_CREDENTIALS = REPO / 'credentials' / 'my-project-omni-507802-9a6505abf0f7.json'
LEDGER = REPO / 'ledger' / 'ledger.jsonl'
STATUS = REPO / 'STATUS.md'
BANNER = '<!-- generated by tools/report.py; do not edit by hand -->'

RELEASES_FOR_DISPLAY = ('castle-batch-v1', 'castle-batch-v2', 'castle-batch-v3')


def load_ledger(path: Path) -> list[dict]:
    import ledger
    return ledger.read(path)


def current_jobs(rows: list[dict]) -> dict:
    import ledger
    return ledger.latest_by_job(row for row in rows if row.get('kind') == 'job')


def releases_table() -> list[dict]:
    out = []
    for path in sorted((REPO / 'releases').glob('*.json')):
        manifest = json.loads(path.read_text(encoding='utf-8'))
        out.append({'release': manifest['release'], 'code_hash': manifest['code_hash'][:8],
                    'full_hash': manifest['code_hash'],
                    'published_utc': manifest.get('published_utc') or '-',
                    'scheme': manifest['hash_scheme'], 'notes': manifest.get('notes', ''),
                    'supersedes': manifest.get('supersedes')})
    return out


def hash_to_release() -> dict:
    """Map code_hash -> releases sharing it, newest first.

    An auxiliary-only change (same identity files) legitimately produces a new
    release with an unchanged code_hash, so this mapping is one-to-many. Callers
    report the newest and mention the rest rather than silently picking one.
    """
    grouped: dict[str, list[dict]] = {}
    for item in releases_table():
        grouped.setdefault(item['full_hash'], []).append(item)
    return {digest: sorted(items, key=lambda i: (i['published_utc'], i['release']), reverse=True)
            for digest, items in grouped.items()}


def render(probe: dict, rows: list[dict]) -> str:
    by_hash = hash_to_release()
    lines = [BANNER, '', '# CASTLE 状态', '',
             f'本文件由 `tools/report.py` 生成，探测时间 **{probe.get("probed_utc", "unknown")}**。',
             '手工修改会在下一次生成时被覆盖；任何云端断言都必须带这个时间戳。', '']

    lines += ['## 已发布 release', '', '| release | code_hash | 发布(UTC) | 哈希方案 | 说明 |',
              '|---|---|---|---|---|']
    for item in releases_table():
        lines.append('| `{release}` | `{code_hash}` | {published_utc} | `{scheme}` | {notes} |'.format(**item))
    lines.append('')

    lines += ['## Batch run 实况', '',
              '| run | pin (release / code_hash) | 阶段 | 完成 | 失败 | 待推进 | 各阶段 Vertex 状态 |',
              '|---|---|---|---:|---:|---:|---|']
    for label, entry in probe.get('runs', {}).items():
        if 'summary' not in entry:
            note = entry.get('error') or entry.get('state', 'unknown')
            lines.append(f'| `{label}` | — | — | — | — | — | {note} |')
            continue
        summary = entry['summary']
        stored = summary.get('code_hash') or ''
        candidates = by_hash.get(stored, [])
        release = summary.get('release') or (candidates[0]['release'] if candidates else '未登记')
        shared = ''
        if len(candidates) > 1:
            others = ', '.join(f"`{c['release']}`" for c in candidates if c['release'] != release)
            shared = f' (同哈希: {others})'
        pin = f'`{release}` / `{stored[:8] or "—"}`{shared}'
        live = entry.get('live_vertex') or {}
        stages = ', '.join(
            f"{stage}: {(info.get('state') or '?').replace('JOB_STATE_', '')}"
            for stage, info in (live or {}).items()) or '—'
        lines.append('| `{}` | {} | {} | {} | {} | {} | {} |'.format(
            label, pin, summary.get('current_stage'), summary.get('completed'),
            summary.get('failures'), summary.get('eligible_next'), stages))
    lines.append('')

    # Stage timing, straight from Vertex's own timestamps. One row per (run, stage),
    # so it is a separate table rather than more columns on the run table.
    timing_rows = []
    for label, entry in probe.get('runs', {}).items():
        for stage, info in (entry.get('live_vertex') or {}).items():
            running = info.get('running_sec')
            successful = info.get('successful_count') or 0
            timing_rows.append({
                'run': label, 'stage': stage,
                'state': (info.get('state') or '?').replace('JOB_STATE_', ''),
                'queued': info.get('queued_sec'), 'running': running,
                'successful': successful,
                'per_clip': round(running / successful, 1) if running and successful else None,
            })
    if timing_rows:
        lines += ['## 各阶段实测耗时（Vertex 时间戳）', '',
                  '| run | 阶段 | 状态 | 排队(s) | 运行(s) | 成功 | s/clip |',
                  '|---|---|---|---:|---:|---:|---:|']
        for row in timing_rows:
            lines.append('| `{}` | {} | {} | {} | {} | {} | {} |'.format(
                row['run'], row['stage'], row['state'],
                row['queued'] if row['queued'] is not None else '—',
                row['running'] if row['running'] is not None else '进行中',
                row['successful'], row['per_clip'] if row['per_clip'] is not None else '—'))
        finished = [r for r in timing_rows if r['per_clip']]
        if finished:
            by_stage: dict[str, list] = {}
            for row in finished:
                by_stage.setdefault(row['stage'], []).append(row['per_clip'])
            parts = [f"{stage} {sum(v)/len(v):.1f} s/clip (n={len(v)})"
                     for stage, v in sorted(by_stage.items())]
            queues = [r['queued'] for r in timing_rows if r['queued'] is not None]
            summary_line = '已完成阶段的均值：' + '；'.join(parts) + '。'
            if queues:
                summary_line += f" 排队均值 {sum(queues)/len(queues):.0f} s（最大 {max(queues):.0f} s）。"
            lines += ['', summary_line]
        lines.append('')

    jobs = current_jobs(rows)
    by_hash = hash_to_release()
    if jobs:
        lines += ['## 已记录的 Job（ledger，最新状态）', '',
                  '| job id | 角色 | 状态 | pin | 说明 |', '|---|---|---|---|---|']
        for job_id, row in sorted(jobs.items(), key=lambda kv: kv[1]['ts_utc']):
            pin = (row.get('pin') or {}).get('release') or '—'
            if pin == '—':
                stored_hash = (row.get('pin') or {}).get('code_hash')
                candidates = by_hash.get(stored_hash or '', [])
                pin = candidates[0]['release'] if candidates else '—'
            note = (row.get('note') or row.get('detail') or '')[:80]
            lines.append(f"| `{job_id.split('/')[-1]}` | {row.get('role')} | {row['status']} | `{pin}` | {note} |")
        lines.append('')

    lines += ['## 尚未实施的能力', '',
              '见 `docs/release-process.md` 第 5 节的勾选表；该表是权威清单，本节不重复维护。', '']
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--credentials', type=Path, default=DEFAULT_CREDENTIALS)
    parser.add_argument('--from-json', type=Path, default=None,
                        help='Render from a saved probe instead of calling the cloud')
    parser.add_argument('--out', type=Path, default=STATUS)
    parser.add_argument('--check', action='store_true',
                        help='Exit non-zero if the file on disk differs from freshly rendered output')
    args = parser.parse_args()

    if args.from_json:
        probe = json.loads(args.from_json.read_text(encoding='utf-8'))
    else:
        import tools.cloud_probe as cloud_probe
        probe = cloud_probe.probe(args.credentials)

    text = render(probe, load_ledger(LEDGER))
    if args.check:
        existing = args.out.read_text(encoding='utf-8') if args.out.is_file() else ''
        # The probe timestamp changes every run; compare the body, not the header line.
        def body(value):
            return [line for line in value.splitlines() if not line.startswith('本文件由')]
        if body(existing) != body(text):
            print(json.dumps({'ok': False, 'error': 'STATUS.md is stale; rerun tools/report.py',
                              'path': str(args.out)}, indent=2))
            return 1
        print(json.dumps({'ok': True, 'path': str(args.out)}, indent=2))
        return 0

    args.out.write_text(text, encoding='utf-8', newline='\n')
    print(json.dumps({'ok': True, 'path': str(args.out), 'probed_utc': probe.get('probed_utc'),
                      'runs': len(probe.get('runs', {})), 'bytes': len(text)}, indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
